services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: backend-api
    ports:
      - "9443:443"   # Puerto HTTPS expuesto en host 9443
      - "8001:8001"  # Puerto para WebSocket
    environment:
      HOST: 0.0.0.0
      PORT: 443
      PYTHONUNBUFFERED: 1
      PYTHONPATH: /app
      SOCKETIO_ASYNC_MODE: asgi
      DB_API: http://smartpay-db-api:8002
      USER_SVC_URL: http://smartpay-db-api:8002
      REDIRECT_URI: https://smartpay-oficial.com/api/v1/google/auth/callback
      CLIENT_SECRET: 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
      CLIENT_ID: 631597337466-dt7qitq7tg2022rhje5ib5sk0eua6t79.apps.googleusercontent.com
      # Configuración de correo electrónico
      SMTP_SERVER: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USERNAME: smartpay.noreply@gmail.com
      # Contraseña de aplicación de Google - con espacios como la mostró Google
      SMTP_PASSWORD: 'jgiz oqck snoj icwz'
      EMAIL_FROM: smartpay.noreply@gmail.com
      RESET_PASSWORD_BASE_URL: https://smartpay-oficial.com/reset-password
    volumes:
      - ..:/app
      - ./logs:/app/logs
      - /etc/ssl/smartpay:/etc/ssl/smartpay:ro  # Certificados SSL
      # Montar Docker socket para Docker-in-Docker
      - /var/run/docker.sock:/var/run/docker.sock
      # Montar directorio padre para acceso a deployments
      - /home/smartpayvps:/host/smartpayvps
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Comando SSL se toma del Dockerfile
    sysctls:
      - net.core.somaxconn=65535
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - smartpay
      
  # Servicio de base de datos
  smartpay-db-v12:
    image: postgres:12
    container_name: docker-smartpay-db-v12-1
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smartpay
    volumes:
      - smartpay-db-prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - smartpay
      
  # Servicio de API de base de datos
  smartpay-db-api:
    image: smartpay-db-api
    container_name: smartpay-db-api
    ports:
      - "8002:8002"
      - "10001:10001"
    environment:
      - PYTHONUNBUFFERED=1
      - WEB_APP_VERSION=0.1.0
      - WEP_APP_TITLE=smartpay-db
      - WEP_APP_DESCRIPTION=Database service for SmartPay
      - ENVIRONMENT=prod
      - POSTGRES_DATABASE_URL=postgres://postgres:postgres@smartpay-db-v12:5432/smartpay
      - DEFAULT_DATA=False
      - PYTHONPATH=/usr/src/app
    volumes:
      - ./logs:/usr/src/app/logs
      - /home/smartpayvps/db-smartpay:/usr/src/app
    working_dir: /usr/src/app
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8002"]
    depends_on:
      smartpay-db-v12:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - smartpay

networks:
  smartpay:
    driver: bridge
    name: smartpay_network

volumes:
  smartpay-db-prod:
    driver: local
    name: smartpay-db-prod
