version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: backend-api
    ports:
      - "8000:8000"
      - "8001:8001"  # Puerto para WebSocket
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - SOCKETIO_ASYNC_MODE=asgi
      - DB_API=http://host.docker.internal:8002
      - USER_SVC_URL=http://host.docker.internal:8002

    volumes:
      - ..:/app
      - ./logs:/app/logs
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

    sysctls:
      - net.core.somaxconn=65535
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
