version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: backend-api
    ports:
      - "8000:8000"
      - "8001:8001"  # Puerto para WebSocket
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - SOCKETIO_ASYNC_MODE=asgi
    volumes:
      - ../app:/app/app
      - ./logs:/app/logs
    restart: unless-stopped
    # Configuración adicional para manejar muchas conexiones
    sysctls:
      - net.core.somaxconn=65535
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
