services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: backend-api
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    volumes:
      - ../app:/app/app
      - ./logs:/app/logs
    restart: unless-stopped
