services:
  api-55c5643a-8043-4b62-af82-69b332111b4f:
    image: docker-api
    # No build context needed as we're using the existing image
    container_name: backend-api-55c5643a-8043-4b62-af82-69b332111b4f
    expose:
      - "8000"
      - "8001"
    environment:
      HOST: 0.0.0.0
      PORT: 8000
      PYTHONUNBUFFERED: 1
      PYTHONPATH: /app
      SOCKETIO_ASYNC_MODE: asgi
      DB_API: http://smartpay-db-api-55c5643a-8043-4b62-af82-69b332111b4f:8002
      USER_SVC_URL: http://smartpay-db-api-55c5643a-8043-4b62-af82-69b332111b4f:8002
      REDIRECT_URI: https://storeok2.smartpay-oficial.com/api/v1/google/auth/callback
      CLIENT_SECRET: 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
      CLIENT_ID: 631597337466-dt7qitq7tg2022rhje5ib5sk0eua6t79.apps.googleusercontent.com
      SMTP_SERVER: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USERNAME: smartpay.noreply@gmail.com
      SMTP_PASSWORD: 'jgiz oqck snoj icwz'
      EMAIL_FROM: smartpay.noreply@gmail.com
      RESET_PASSWORD_BASE_URL: https://storeok2.smartpay-oficial.com/reset-password
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.storeok2.rule=Host(`storeok2.smartpay-oficial.com`)"
      - "traefik.http.routers.storeok2.entrypoints=https"
      - "traefik.http.routers.storeok2.tls=true"
      - "traefik.http.routers.storeok2.tls.certresolver=letsencrypt"
      - "traefik.http.services.storeok2.loadbalancer.server.port=8000"
      # WebSocket configuration
      - "traefik.http.routers.storeok2-ws.rule=Host(`storeok2.smartpay-oficial.com`) && PathPrefix(`/ws`)"
      - "traefik.http.routers.storeok2-ws.entrypoints=https"
      - "traefik.http.routers.storeok2-ws.tls=true"
      - "traefik.http.routers.storeok2-ws.tls.certresolver=letsencrypt"
      - "traefik.http.services.storeok2-ws.loadbalancer.server.port=8001"
    # No need to mount volumes as we're using the existing image
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--no-use-colors"]
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    sysctls:
      - net.core.somaxconn=65535
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - smartpay-55c5643a-8043-4b62-af82-69b332111b4f
      - traefik-public

  smartpay-db-api-55c5643a-8043-4b62-af82-69b332111b4f:
    image: smartpay-db-api
    container_name: smartpay-db-api-55c5643a-8043-4b62-af82-69b332111b4f
    expose:
      - "8002"
    environment:
      HOST: 0.0.0.0
      PORT: 8002
      PYTHONUNBUFFERED: 1
      PYTHONPATH: /app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.db-storeok2.rule=Host(`db-storeok2.smartpay-oficial.com`)"
      - "traefik.http.routers.db-storeok2.entrypoints=https"
      - "traefik.http.routers.db-storeok2.tls=true"
      - "traefik.http.routers.db-storeok2.tls.certresolver=letsencrypt"
      - "traefik.http.services.db-storeok2.loadbalancer.server.port=8002"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8002", "--no-use-colors"]
    restart: unless-stopped
    networks:
      - smartpay-55c5643a-8043-4b62-af82-69b332111b4f
      - traefik-public

networks:
  smartpay-55c5643a-8043-4b62-af82-69b332111b4f:
    driver: bridge
  traefik-public:
    external: true
